### ISSUE TITLE
"Framework not found Pushwoosh"

### ISSUE THREAD

**Issue by jlstr** [Pushwoosh/pushwoosh-phonegap-plugin#171]
Hello, I have this issue that was previously closed without a clear answer...
I have a **linker error** in XCode the moment I add **Pushwoosh.framework**

![github_issue_1](https://cloud.githubusercontent.com/assets/583016/14544474/da8bfc68-025e-11e6-874d-2855ddc875be.jpg)

Here's the SDK (framework):

![github_issue_2](https://cloud.githubusercontent.com/assets/583016/14544491/ec58590a-025e-11e6-9a11-bc416c0b353e.jpg)

I have run out of ideas as to how to finally solve this issue, Any help is totally appreciated.

**Comment by wfhm** [comment]
Hello Jose,

In the previous thread @shaders  recommended you to use the latest plugin version. I had just tried it with our [sample](https://github.com/Pushwoosh/pushwoosh-phonegap-cordova-sample/tree/master/Phonegap-iOS-Android-WP) and it worked, so could you please let us know whether the issue is reproducible with it on your side?

**Comment by jlstr** [comment]
Hello @wfhm, Thank you for your reply. The solution is to use this line of code (which @shaders pointed out as well) `var pushNotification = cordova.require("pushwoosh-cordova-plugin.PushNotification");`

And additionally, **NOT using the Pushwoosh.framework** SDK as a library inside XCode. If you include it like I did, it will cause the infamous **linker error** in XCode. This however, tells me the documentation or quick steps guide should be explicit about the Need of using that SDK that comes bundled with the plugin installation.

Anyways, for now this one is solved and thank you once more for your reply.
