### ISSUE TITLE
Android issue - after updating an app with pushwoosh 5.1.2-1 + plugin ID  - Help!

### ISSUE THREAD

**Issue by mekemike** [Pushwoosh/pushwoosh-phonegap-plugin#190]
So, after updating(fully working on IOS + Android) an app compiling on PGB, I updated the plug in ID as (https://github.com/Pushwoosh/phonegap-build-sample-app/commit/de2d0a354953dfaa2495bcf571a9f2d760842ccf), with the latest version of pushwoosh.

Working 100% on IOS. On Android though, it seems to register then stop there, display alert token. I've tried rolling back the version etc(no push), nothing seems to work. Set up is exactly the same as before, except for the updated Plug in ID.

I have used the latest PGB and 5.2.0, I'm a bit stuck here :(

Any ideas?! What am I missing here? I feel like it's quite obvious, but I'm just missing it...

**Comment by wfhm** [comment]
Hi, could you please specify what exactly the issue is? Do I understand you correctly that your device is registering properly and showing an alert with a token? What happens after that? Does it crash or just stuck or smth else? 

Also which plugin did you use? Was it pushwoosh-cordova-plugin? Please note that when compiling with PhoneGap Build tool you should use pushwoosh-pgb-plugin.

**Comment by mekemike** [comment]
Hey, thanks for your reply.

It is registering, and displaying an alert with a token. Then dismiss. Push notifications do not display. No crash, or anything else.

It is pushwoosh-pgb-plugin.

**Comment by wfhm** [comment]
Are notifications not being shown in foreground or in background? Are there anything in the log when receiving notification?

At last, does the sample work for you? It's the best place to start with:

https://github.com/Pushwoosh/phonegap-build-sample-app
