### ISSUE TITLE
iOs Universal Links not working

### ISSUE THREAD

**Issue by lpender** [Pushwoosh/pushwoosh-phonegap-plugin#248]
When I tap a link to my app (i.e. http://beta.flareis.cool/test) in i.e. Google Inbox, it opens the link directly in the app,

This is due to my integration with:

https://github.com/nordnet/cordova-universal-links-plugin

However, tapping pushwoosh notifications opens the app, which opens the link in a safari browser.

Using 6.4.0

Thanks!

**Comment by wfhm** [comment]
Hi,

This is actually an expected behaviour of cordova-universal-links-plugin;

If you want to achieve a different behaviour you might want to use [Deep Linking functionality](http://docs.pushwoosh.com/docs/deep-linking). 

Below you can find a Cordova plugin used for handling deep links:

https://github.com/EddyVerbruggen/Custom-URL-scheme
