### ISSUE TITLE
Foreground push doesn't work on iPhone

### ISSUE THREAD

**Issue by michaeloki** [Pushwoosh/pushwoosh-phonegap-plugin#281]
Foreground push behaves differently on an iPhone. When the app icon is clicked directly, the push message doesn't become visible until a user clicks on the item from the notification banner.

**Comment by wfhm** [comment]
Hi Michael,

This is an expected behavior. Pushwoosh SDK listens for two events - `push-receive` and `push-notification`.

`push-receive` fires when a push is received. If your app is in foreground, it is triggered instantly; if it is in background, it is triggered when you open your app by clicking on a push notification.

`push-notification` fires when a notification is clicked, regardless of whether your app is in foreground or in background. 

Therefore, if you do not interact with a notification at all, `push-notification` will never fire, and `push-receive` will only fire in foreground.
