### ISSUE TITLE
Push notification doesn't show when notification banner is ignored

### ISSUE THREAD

**Issue by michaeloki** [Pushwoosh/pushwoosh-phonegap-plugin#282]
When a user clicks on the app icon directly  from the main menu (on iOS), the notification doesn't show unless the user clicks on the notification item from the banner. 
Is there an API to do this issue on iOS?

**Comment by wfhm** [comment]
Hey,

Could you please elaborate on this issue? What do you mean by "notification doesn't show"? Please note that iOS notifications are not handled in background unless it is opened - you have to interact with a notification, otherwise your application will never know it is actually received. *This is a default iOS behavior and we can do nothing to it.*

The only exception is so called iOS silent pushes, which are automatically handled when received, however they do not show a notification and do not play a sound, and can only be handled when recieved in a non-closed app (foreground or background). To send a silent push you should check a checkbox in Send Push tab in Control Panel or add "ios_silent":1 key to your /createMessage API request.
