### ISSUE TITLE
App removed from google play store

### ISSUE THREAD

**Issue by ipehimanshu** [Pushwoosh/pushwoosh-phonegap-plugin#346]
Hello 

we are using pushwoosh-cordova-plugin with 7.18.11 version and today google removed our 5 apps from play store with below reason,

![image](https://user-images.githubusercontent.com/26652038/114009136-833d4a80-9880-11eb-9a04-f0b87685ebd3.png)

So please help us to keep published our apps.

Thanks

**Comment by wfhm** [comment]
Hello,

Thank you for contacting us!

You may receive a notification from Google stating that your Android app doesn’t meet the privacy policy or prominent disclosure requirements because your app is uploading the information on users’ installed applications via Pushwoosh SDK.

Older versions of Pushwoosh Android SDK (6.2.4 and below) had methods to query the list of installed packages on the device. As per the upcoming changes in the Developer program policy, it may require prominent disclosure and changes to the privacy policy to keep the application published.

We strongly recommend you update your SDK to the latest version (6.2.7 at the moment of publication) to meet the newest requirements from the Google Play Store.

The Cordova plugin will be also updated in the nearest time - I will notify you as soon as it will be done!

Please, stay tuned!

Kind regards,
Kate Biluta
Pushwoosh Team

* * *
Please visit our **Help Center** where you can manage all your support requests and find solutions to the vast number of questions:

https://help.pushwoosh.com/hc/

**Comment by mg** [comment]
Hi, this is happening to us (Landsbankinn) as well. We've updated to 8.1.1 and are pushing it to the play store, this will fix the issue?

**Comment by wfhm** [comment]
Dear,

We have just released the new Cordova SDK plugin version. Here you will find it:

https://github.com/Pushwoosh/pushwoosh-phonegap-plugin

Then the issue should be gone.

Please let me know if I could be of any further help!

Kind regards,
Kate Biluta
Pushwoosh Team
