### ISSUE TITLE
The alert title shows index.html

### ISSUE THREAD

**Issue by ianchan0817** [Pushwoosh/pushwoosh-phonegap-plugin#36]
Can I disable this? or change it to my title instead of the url path?
Can it be parameter set to show it?

**Comment by chornbe** [comment]
Seriously, that's the answer? Why is everything so darned inconsistent?

**Comment by shaders** [comment]
http://lmgtfy.com/?q=phonegap+alert+index+html&l=1
http://stackoverflow.com/questions/10486403/how-to-change-the-default-heading-of-alert

**Comment by chornbe** [comment]
Shaders, do you work for pushwoosh? Are you pushwoosh? Because every single thing I see you post on is that kind of snarky and dismissive crap. Your customer service gene is poorly expressed. Seriously, man... just dial back the snark and understand lots of people are trying to use the product and services, and the documentation and occasional inconsistencies are beyond a little frustrating.

Back off the attitude and just help people solve their problems. Lots of other companies are providing the same kinds of services, you know?
