### ISSUE TITLE
iOS: Listeners conflict with @capacitor/local-notifications

### ISSUE THREAD

**Issue by zarko-tg** [Pushwoosh/pushwoosh-phonegap-plugin#392]
Basically, looking at the surface of things, having the Pushwoosh plugin running next to the @capacitor/local-notifications makes the listeners of the latter stop working on Capacitor iOS.
@capacitor/local-notifications "localNotificationReceived" & "localNotificationActionPerformed" are kinda important from a standpoint of a user/UI flow so I'm hoping this can get fixed or worked around in either of the plugins.

As [wfhm](https://github.com/wfhm) put it nicely in https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/94#issuecomment-1706602867 :

> It looks like both @capacitor/local-notifications and pushwoosh-cordova-plugin plugins try to use methods of
> UNUserNotificationCenterDelegate, and the Capacitor plugin doesn't expect other plugins to swizzle these methods (like our
> plugin does). So the swizzled versions of these methods do not trigger callbacks of the local-notifications plugin at all.
> With Ionic Capacitor you should still have access to the native iOS project, so theoretically you can manually update your
> AppDelegate to let both plugins access UNUserNotificationCenterDelegate methods, however it might depend on the
> local-notifications implementation of these methods in their plugin.

A reproduction code/project is available with the comment here: https://github.com/Pushwoosh/pushwoosh-ios-sdk/issues/94#issuecomment-1693204785

**Comment by wfhm** [comment]
@zarko-tg I apologize for such a delayed response. I'll look into the @capacitor/local-notifications plugin and try to create an example project for you.

Stay tuned!

**Comment by wfhm** [comment]
@zarko-tg Okay, so there is a workaround but it is quite complicated, and our standard approach to resolving delegate conflicts is not applicable. 

Right now, if you disable Pushwoosh notification delegate directly in the plugin, you are still left with Capacitor delegate overwriting your app's delegate during [CapacitorBridge initialization](https://github.com/ionic-team/capacitor/blob/main/ios/Capacitor/Capacitor/CapacitorBridge.swift#L200), and it happens when Capacitor core is initialized, not just the plugin. So we cannot just create a custom router delegate that will distribute notifications between Pushwoosh and **local-notifications** plugin without messing with Capacitor initialization.

The solution I ended up with is creating a helper class inside the **local-notifications** plugin that will receive pushes and forward it to Pushwoosh handler methods.

* First, add Pushwoosh XCFramework to your Xcode project pods, for example, using Swift Package Manager. You can follow the first part of this guide:
https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/ios-push-notifications/setting-up-pushwoosh-ios-sdk/swift-package-manager-setup#integration

* Add the framework to **Pods/CapacitorLocalNotifications** target:

<img width="790" alt="Screenshot 2023-10-09 at 19 56 45" src="https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/assets/13344781/22856bd2-5c3a-45af-bdc8-e5992c5104a7">

* Then, create a new class in the CapacitorLocalNotifications directory (let's call it PushwooshNotificationHandler):

<img width="434" alt="Screenshot 2023-10-09 at 19 45 50" src="https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/assets/13344781/846d2b97-8863-4c6b-80e8-12a919a318fa">

* Replace its code with the code of `PushwooshNotificationHandler.swift` from the attached archive

* Then, we need to modify the **local-notifications** plugin code to use this class as push notifications handler. Replace the code of `LocalNotificationsPlugin.swift` with the one you can find in the attached archive.

* Finally, disable Pushwoosh notification center delegate in the Pushwoosh plugin by removing (or commenting out) [this line](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/blob/0c5573ecd6d1e9dbfd98a84feec2f51b49c1fb2c/src/ios/PushNotification.m#L143):
```
[UNUserNotificationCenter currentNotificationCenter].delegate = [PushNotificationManager pushManager].notificationCenterDelegate;
```

That should be enough to make Capacitor's `NotificationRouter` class serve as a single delegate in your app that can also receive Pushwoosh notifications. However, for some reason, received push notifications generate a local notification with the same content, so, to work around it, you can also modify the the code of **Capacitor/NotificationRouter** class by adding the following check to the `willPresent:withCompletionHandler` method:
```
public func userNotificationCenter(_ center: UNUserNotificationCenter,
                                       willPresent notification: UNNotification,
                                       withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        let presentationOptions: UNNotificationPresentationOptions?

        if notification.request.trigger?.isKind(of: UNPushNotificationTrigger.self) == true {
            presentationOptions = pushNotificationHandler?.willPresent(notification: notification)
        } else {
            if let userInfo = notification.request.content.userInfo["pw_push"] {
                return
            }
            presentationOptions = localNotificationHandler?.willPresent(notification: notification)
        }

        completionHandler(presentationOptions ?? [])
    }
```
You can also find its code in the archive below.


[Archive.zip](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/files/12848285/Archive.zip)

**Comment by wfhm** [comment]
We are planning to rework delegate swizzling in our plugins to make resolving such conflicts much easier, so I will keep this issue open until there is any news.

**Comment by zarko-tg** [comment]
Hi @wfhm,
Firstly, apologies for not being able to check the workaround due to time constraints.
I'll be checking out the new version for iOS but we now get an (unrelated?) Android failure:

```
> Task :app:processReleaseMainManifest FAILED
/Users/foo/bar/android/app/src/main/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 23 cannot be smaller than version 26 declared in library [com.pushwoosh:pushwoosh-inbox-ui:6.7.0] /Users/foo/.gradle/caches/transforms-3/0f75b005e76e163215622787ea7bc654/transformed/pushwoosh-inbox-ui-6.7.0/AndroidManifest.xml as the library might be using APIs not available in 23
        Suggestion: use a compatible library with a minSdk of at most 23,
                or increase this project's minSdk version to at least 26,
                or use tools:overrideLibrary="com.pushwoosh.inbox.ui" to force usage (may lead to runtime failures)

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.
```

I don't think we can move (so high) from 23 for the time being. And we don't even use pushwoosh-inbox-ui.
What'd be the right thing to do about it?

**Comment by wfhm** [comment]
@zarko-tg please let me check if we can downgrade minSdkVersion and I'll get back to you shortly.

**Comment by wfhm** [comment]
@zarko-tg Please try the 8.3.18 release - minSdkVersion was reverted back to 23.

**Comment by akiselev-pushwoosh** [comment]
@zarko-tg Small update. Please, try the 8.3.19 release.

**Comment by zarko-tg** [comment]
Thanks for that, it seems to have solved the problem!

**Comment by zarko-tg** [comment]
Hi there,

I'll write here and briefly now since it seems related but I can open a new issue if needed.
We seem to have a rather important regression since ver. 8.3.25 which used iOS library 6.5.8.
https://github.com/Pushwoosh/pushwoosh-ios-sdk/releases/tag/6.5.8
"Change: * reworked application:didFinishLaunchingWithOptions: swizzling logics"

Basically since then our app seems to have sort of broken push system in two cases:
1. When the app is backgrounded (not shown, active in system background, not force closed), and the user taps the received Pushwoosh system notification, the plugin's getLaunchNotification function now always returns null for the "notification" key. We've always called getLaunchNotification as soon our app comes back into foreground, and when 
2. When the app is in foreground and a push event happens / is expected, the 'push-receive' listener no longer triggers.

Any idea what's going on?

**Comment by zarko-tg** [comment]
Ok, I have an Ionic/Capacitor reproduction case/project now, please find it in attachment. The project has no dependencies on @capacitor/local-notifications.

Instructions:
1. Replace all "com.pushwoosh.test" with a bundle ID that works for push notifications.
2. Set "DEVELOPMENT_TEAM[sdk=iphoneos*]" to your development team ID
3. Set "PROVISIONING_PROFILE_SPECIFIER[sdk=iphoneos*]" to the name of your prov. profile
4. In home.page.ts, set value for appid.
5. npm install
6. ionic cap run ios --device

Out of the box it should work as expected - it depends on pushwoosh-cordova-plugin ver. 8.3.24.
Once updated to 8.3.25 (or the latest 8.3.28) 'push-receive' and getLaunchNotification no longer work as expected.

[fg-push-test.zip](https://github.com/user-attachments/files/16837118/fg-push-test.zip)

**Comment by zarko-tg** [comment]
Have you been able to reproduce?

**Comment by enginseer-dev** [comment]
Hello, @zarko-tg, at this moment this task in queue. We'll let you know when check it. Kindly ask you stay tuned.

**Comment by zarko-tg** [comment]
FYI, I though about reverting to 8.3.24 since this seems to be taking a lot of time to resolve.
But it turns out that while the 'push-receive' listener works with it, the getLaunchNotification returns null at cold launch. We're in some sort of a problem loop here :/

**Comment by enginseer-dev** [comment]
Hi, @zarko-tg, appreciate your patience!
After detailed analysis, we were able to find a tricky bug in swizzling in the core iOS SDK. Our team is already working on a fix and in the near future we will release a new version, as well as update all plugins. I will report news here additionally. Thank you for understanding.

**Comment by zarko-tg** [comment]
@enginseer-dev Thank you, good to hear of the progress.
